[package]
name = "bevy_spatial"
description = "A crate for tracking bevy entities in spatial indices."
documentation = "https://docs.rs/bevy_spatial"
version = "0.4.0"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["gamedev", "bevy", "spatial", "kdtree", "rtree"]
repository = "https://github.com/laundmo/bevy-spatial"
readme = "README.md"
authors = ["laundmo"]

[dependencies]
bevy = { version = "0.10", default-features = false }
# R*-Tree dependencies
rstar = { version = "0.10", optional = true }
# KD-Tree dependencies
kd-tree = { version = "0.5.1", optional = true, features = ["rayon"] }
typenum = { version = "1.15.0", optional = true }
num-traits = { version = "0.2.15", optional = true }


[features]
default = []
rstar = ["dep:rstar"]
kdtree = ["dep:kd-tree", "dep:typenum", "dep:num-traits"]

[dev-dependencies]
bevy = { version = "0.10" }
# bevy-aabb-instancing = "0.3.0"
wasm-server-runner = "0.4.0"

# without the rayon feature 
[target.'cfg(target_arch = "wasm32")'.dependencies]
kd-tree = { version = "0.5.1", optional = true }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release-with-debug]
inherits = "release"
debug = true

[[example]]
name = "distance2d"
required-features = ["kdtree"]

[[example]]
name = "distance3d"
required-features = ["rstar"]

[[example]]
name = "modify_timestep"
required-features = ["kdtree"]

[[example]]
name = "movetowards"
required-features = ["rstar"]

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
